### ISSUE TITLE
can this be added as query parameters ?

### ISSUE THREAD

**Issue by sandys** [AbsoluteCommerce/Magento2-CacheBust#3]
e,g, "?version=XXXX" instead of make it part of URL (which needs nginx/apache config).

many hosting sites do not let access to nginx/apache config.

**Comment by josephmcdermott** [comment]
Hi and sorry for not replying in such a long time. The current implementation works on the base URL so won't allow a suffix, but it is a good suggestion that we will investigate and see whether it can be included as an alternative method of cache busting.

**Comment by josephmcdermott** [comment]
Had a look at this and tried some implementations, but it is quite complicated due to the way Magento builds its URLs. A lot of the JavaScript URLs are generated by RequireJS on the frontend by using a base URL, so we end up with `https://yoursite.com/some/path/?v=12345/the-file.js` which is no good.

It is likely possible but will take a little time, so if you wanted to get in touch we could look at putting together a bespoke proposal for your project(s), but for the time being this is off the roadmap for the public extension.
